const FETCH_GROUP = 'FETCH_GROUP';
const FETCH_GROUP_SUCCESS = 'FETCH_GROUP_SUCCESS';
const FETCH_GROUP_FAILURE = 'FETCH_GROUP_FAILURE';


export{FETCH_GROUP, FETCH_GROUP_SUCCESS, FETCH_GROUP_FAILURE}
