const FETCH_VARIETY = 'FETCH_VARIETY';
const FETCH_VARIETY_SUCCESS = 'FETCH_VARIETY_SUCCESS';
const FETCH_VARIETY_FAILURE = 'FETCH_VARIETY_FAILURE';

export { FETCH_VARIETY, FETCH_VARIETY_SUCCESS, FETCH_VARIETY_FAILURE };
